language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

before_install:
    - sudo apt-add-repository ppa:chris-lea/node.js -y
    - sudo apt-get update
    - sudo apt-get install nodejs ditaa

install:
    - sudo pip install pelican 
    - sudo pip install jinja2
    - sudo pip install babel
    - sudo pip install beautifulsoup4
    - sudo npm install -g less
    - sudo ln -s /bin/true /bin/opencc
    - wget http://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml
    - echo "#! /bin/sh" > plantuml
    - echo 'exec java -jar /opt/plantuml/plantuml.jar "$@"' >> plantuml
    - install -m 755 -D plantuml /usr/bin/plantuml
    - plantuml -version

script:
    - git clone https://github.com/farseerfc/pelican-plugins plugins
    - git clone https://github.com/farseerfc/pelican-bootstrap3 theme
    - mkdir output
    - make html