language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

before_install:
    - sudo apt-add-repository ppa:chris-lea/node.js -y
    - sudo apt-get update
    - sudo apt-get install nodejs ditaa doxygen

install:
    - sudo pip install pelican 
    - sudo pip install jinja2
    - sudo pip install babel
    - sudo pip install beautifulsoup4
    - sudo npm install -g less
    - wget http://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O plantuml.jar
    - sudo mkdir -p /opt/plantuml
    - sudo cp plantuml.jar /opt/plantuml
    - echo "#! /bin/sh" > plantuml
    - echo 'exec java -jar /opt/plantuml/plantuml.jar "$@"' >> plantuml
    - sudo install -m 755 -D plantuml /usr/bin/plantuml
    - plantuml -version
    - wget https://bintray.com/artifact/download/byvoid/opencc/opencc-1.0.2.tar.gz
    - tar xf opencc-1.0.2.tar.gz
    - cd opencc-1.0.2 && make && sudo make install
    - opencc --version

script:
    - git clone https://github.com/farseerfc/pelican-plugins plugins
    - git clone https://github.com/farseerfc/pelican-bootstrap3 theme
    - mkdir output
    - make html