language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

before_install:
    - sudo apt-add-repository ppa:chris-lea/node.js -y
    - sudo apt-get update
    - sudo apt-get install nodejs 

install:
    - sudo pip install pelican 
    - sudo pip install jinja2
    - sudo pip install babel
    - sudo npm install -g less
    - sudo ln -s /bin/true /bin/opencc

script:
    - git clone https://github.com/farseerfc/pelican-plugins plugins
    - git clone https://github.com/farseerfc/pelican-bootstrap3 theme
    - mkdir output
    - make html